from __future__ import annotations

import uuid
from decimal import Decimal
from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, Numeric, String, ForeignKey
from sqlalchemy.dialects.postgresql import UUID as PG_UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import AuditMixin, Base


class AIRecommendation(Base, AuditMixin):
    """Recommendation generated by an AI/ML model for a business object."""

    __tablename__ = "ai_recommendations"

    object_type: Mapped[str] = mapped_column(String(100), nullable=False)
    object_id: Mapped[uuid.UUID] = mapped_column(PG_UUID(as_uuid=True), nullable=False)
    recommendation: Mapped[dict | None] = mapped_column(JSONB)
    confidence: Mapped[Decimal | None] = mapped_column(Numeric(5, 2))
    generated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
