"""
OpenS2P – Event Type Definitions
==================================
Event types and payload definitions for the domain event system.
"""

# Workflow events
WORKFLOW_STARTED = "WORKFLOW_STARTED"
WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
WORKFLOW_REJECTED = "WORKFLOW_REJECTED"

# Supplier events
SUPPLIER_CREATED = "SUPPLIER_CREATED"
SUPPLIER_APPROVED = "SUPPLIER_APPROVED"
SUPPLIER_BLOCKED = "SUPPLIER_BLOCKED"

# Contract events
CONTRACT_CREATED = "CONTRACT_CREATED"
CONTRACT_ACTIVATED = "CONTRACT_ACTIVATED"
CONTRACT_RENEWED = "CONTRACT_RENEWED"

# Purchase Requisition events
PR_SUBMITTED = "PR_SUBMITTED"
PR_APPROVED = "PR_APPROVED"
PR_REJECTED = "PR_REJECTED"

# Purchase Order events
PO_CREATED = "PO_CREATED"
PO_SENT = "PO_SENT"
PO_CLOSED = "PO_CLOSED"

# Invoice events
INVOICE_SUBMITTED = "INVOICE_SUBMITTED"
INVOICE_MATCHED = "INVOICE_MATCHED"
INVOICE_APPROVED = "INVOICE_APPROVED"
INVOICE_PAID = "INVOICE_PAID"

# All known event types
ALL_EVENTS = [
    WORKFLOW_STARTED,
    WORKFLOW_COMPLETED,
    WORKFLOW_REJECTED,
    SUPPLIER_CREATED,
    SUPPLIER_APPROVED,
    SUPPLIER_BLOCKED,
    CONTRACT_CREATED,
    CONTRACT_ACTIVATED,
    CONTRACT_RENEWED,
    PR_SUBMITTED,
    PR_APPROVED,
    PR_REJECTED,
    PO_CREATED,
    PO_SENT,
    PO_CLOSED,
    INVOICE_SUBMITTED,
    INVOICE_MATCHED,
    INVOICE_APPROVED,
    INVOICE_PAID,
]
