"""add_integration_tables

Revision ID: 1d5fdef7b1e1
Revises: 832d1ea2a628
Create Date: 2026-07-08 16:38:37.172366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d5fdef7b1e1'
down_revision: Union[str, Sequence[str], None] = '832d1ea2a628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_connections',
    sa.Column('connection_name', sa.String(length=200), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('endpoint_url', sa.String(length=2000), nullable=True),
    sa.Column('auth_type', sa.String(length=50), nullable=True),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_connected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_connections_tenant_id'), 'integration_connections', ['tenant_id'], unique=False)
    op.create_table('external_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('internal_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('external_system', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_references_connection_id'), 'external_references', ['connection_id'], unique=False)
    op.create_index(op.f('ix_external_references_tenant_id'), 'external_references', ['tenant_id'], unique=False)
    op.create_table('field_mappings',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('external_field', sa.String(length=200), nullable=False),
    sa.Column('internal_field', sa.String(length=200), nullable=False),
    sa.Column('transform_expression', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_mappings_connection_id'), 'field_mappings', ['connection_id'], unique=False)
    op.create_index(op.f('ix_field_mappings_tenant_id'), 'field_mappings', ['tenant_id'], unique=False)
    op.create_table('integration_runs',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_runs_connection_id'), 'integration_runs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_integration_runs_tenant_id'), 'integration_runs', ['tenant_id'], unique=False)
    op.create_table('integration_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=True),
    sa.Column('object_id', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['integration_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_logs_run_id'), 'integration_logs', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_logs_run_id'), table_name='integration_logs')
    op.drop_table('integration_logs')
    op.drop_index(op.f('ix_integration_runs_tenant_id'), table_name='integration_runs')
    op.drop_index(op.f('ix_integration_runs_connection_id'), table_name='integration_runs')
    op.drop_table('integration_runs')
    op.drop_index(op.f('ix_field_mappings_tenant_id'), table_name='field_mappings')
    op.drop_index(op.f('ix_field_mappings_connection_id'), table_name='field_mappings')
    op.drop_table('field_mappings')
    op.drop_index(op.f('ix_external_references_tenant_id'), table_name='external_references')
    op.drop_index(op.f('ix_external_references_connection_id'), table_name='external_references')
    op.drop_table('external_references')
    op.drop_index(op.f('ix_integration_connections_tenant_id'), table_name='integration_connections')
    op.drop_table('integration_connections')
    # ### end Alembic commands ###
