"""add_receipt_number_to_receipts

Revision ID: 1e1f8ecd249c
Revises: cc6e90b3f0a1
Create Date: 2026-07-10 07:50:27.799225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1f8ecd249c'
down_revision: Union[str, Sequence[str], None] = 'cc6e90b3f0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'po_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('purchase_requisitions', 'pr_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('receipts', sa.Column('receipt_number', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'receipts', ['receipt_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipts', type_='unique')
    op.drop_column('receipts', 'receipt_number')
    op.alter_column('purchase_requisitions', 'pr_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('purchase_orders', 'po_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
