"""add_workflow_engine_fields

Revision ID: 832d1ea2a628
Revises: a3b8e7ea5a41
Create Date: 2026-07-08 16:29:10.919430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '832d1ea2a628'
down_revision: Union[str, Sequence[str], None] = 'a3b8e7ea5a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_tasks', sa.Column('step_name', sa.String(length=100), nullable=True))
    op.add_column('approval_tasks', sa.Column('assigned_role', sa.String(length=100), nullable=True))
    op.add_column('approval_tasks', sa.Column('comments', sa.String(), nullable=True))
    op.add_column('workflow_instances', sa.Column('workflow_name', sa.String(length=100), nullable=True))
    op.add_column('workflow_instances', sa.Column('current_step', sa.Integer(), nullable=True))
    op.add_column('workflow_instances', sa.Column('wf_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_instances', 'wf_metadata')
    op.drop_column('workflow_instances', 'current_step')
    op.drop_column('workflow_instances', 'workflow_name')
    op.drop_column('approval_tasks', 'comments')
    op.drop_column('approval_tasks', 'assigned_role')
    op.drop_column('approval_tasks', 'step_name')
    # ### end Alembic commands ###
